CREATE TABLE IF NOT EXISTS product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
  id_1c TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  name_1c TEXT,

  product_group_id BIGINT NOT NULL REFERENCES product_group(id),
  product_vid_id BIGINT NOT NULL REFERENCES product_vid(id),
  registrator_id BIGINT NOT NULL REFERENCES registrator(id),
  brend_id BIGINT REFERENCES brend(id),
  country_id BIGINT REFERENCES country(id),
  Vid_modeli_id BIGINT REFERENCES Vid_modeli(id),

  artikul TEXT NOT NULL,
  base_ed TEXT NOT NULL,
  description TEXT,
  material_inside TEXT,
  material_podoshva TEXT,
  material_up TEXT,
  sex INT,
  product_folder TEXT,
  main_color TEXT,
  public_web BOOLEAN,
 
 changed_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, 
 create_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS product_idx ON product (id, registrator_id, id_1c)