CREATE TABLE IF NOT EXISTS kaspi_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,

  first_size TEXT NOT NULL,
  last_size TEXT NOT NULL,
  size_kaspi TEXT[] NOT NULL,
  name_kaspi TEXT NOT NULL UNIQUE,
  title_kaspi  TEXT NOT NULL, 
  gender_kaspi TEXT[] NOT NULL,
  model_kaspi TEXT[] NOT NULL,

  changed_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, 
  create_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE kaspi_categories IS 'Список категорий из Kaspi и их главные параметры';