CREATE TABLE IF NOT EXISTS kaspi_export_goods_registry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,

  kaspi_organization_id BIGINT NOT NULL REFERENCES kaspi_organizations (id) NOT NULL,
  product_id BIGINT NOT NULL REFERENCES product (id) NOT NULL,

  sended_body TEXT not null,
  sended_category TEXT not null,
  sended_status INT not null,
  response_id TEXT,
  response_status TEXT,

  changed_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, 
  create_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS kaspi_export_goods_registry_idx
ON kaspi_export_goods_registry (kaspi_organization_id, product_id, sended_status, sended_category);

COMMENT ON TABLE kaspi_export_goods_registry IS 'Хранение истории экспорта товаров в Kaspi';

COMMENT ON COLUMN kaspi_export_goods_registry.sended_body IS 'JSON уходящий на Kaspi';
COMMENT ON COLUMN kaspi_export_goods_registry.sended_category IS 'категория типа Master - Boots for babies';  
COMMENT ON COLUMN kaspi_export_goods_registry.sended_status IS 'статус-код получили за POST запрос на импорт - 200, 400';  
COMMENT ON COLUMN kaspi_export_goods_registry.response_id IS 'id из возвращаемого ответа как 6dd2cf12-2cd4-4992-bd1f-c081db01afea';  
COMMENT ON COLUMN kaspi_export_goods_registry.response_status IS 'текст как UPLOADED';  
