CREATE TABLE IF NOT EXISTS qnt_price_registry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,

  sum DECIMAL NOT NULL,
  qnt DECIMAL NOT NULL,
  operation_date TIMESTAMPTZ NOT NULL,
  discount_percent DECIMAL,
  discount_begin TIMESTAMPTZ,
  discount_end TIMESTAMPTZ,

  store_id BIGINT NOT NULL REFERENCES store (id) NOT NULL,
  product_id BIGINT NOT NULL REFERENCES product (id) NOT NULL,
  price_vid_id BIGINT NOT NULL REFERENCES price_vid (id) NOT NULL,  
  size_id BIGINT NOT NULL REFERENCES size (id),
  registrator_id BIGINT NOT NULL REFERENCES registrator (id) NOT NULL,
  product_group_id BIGINT NOT NULL REFERENCES product_group (id) NOT NULL,
  vid_modeli_id BIGINT NOT NULL REFERENCES vid_modeli (id),

  size_name_1c TEXT,
  product_name TEXT NOT NULL,
  product_create_date TIMESTAMPTZ NOT NULL,

 changed_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, 
 create_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS qnt_price_idx
ON qnt_price_registry (registrator_id, product_id, product_create_date)