CREATE TABLE IF NOT EXISTS image_registry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,

  main BOOLEAN NOT NULL DEFAULT FALSE,
  main_change_date TIMESTAMPTZ NOT NULL,
  resolution TEXT,
  size INT NOT NULL,
  full_name TEXT NOT NULL,
  name TEXT NOT NULL UNIQUE,
  path TEXT NOT NULL,

  operation_date TIMESTAMPTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  active_change_date TIMESTAMPTZ NOT NULL,
  
  product_id BIGINT NOT NULL REFERENCES product (id) NOT NULL,
  registrator_id BIGINT NOT NULL REFERENCES registrator (id),

 changed_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, 
 create_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX IF NOT EXISTS image_registry_idx ON image_registry (product_id, active, main );